<a href="https://colab.research.google.com/github/sanchitasontakke07-exe/Day_20/blob/main/Day20_(car_dataset).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [5]:
from google.colab import files
uploaded=files.upload()
df=pd.read_csv("/content/Car.csv")
df

Saving Car.csv to Car (2).csv

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,Fiesta,2017,12000,Automatic,15944,Petrol,150,57.7,1.0
1,Focus,2018,14000,Manual,9083,Petrol,150,57.7,1.0
2,Focus,2017,13000,Manual,12456,Petrol,150,57.7,1.0
3,Fiesta,2019,17500,Manual,10460,Petrol,145,40.3,1.5
4,Fiesta,2019,16500,Automatic,1482,Petrol,145,48.7,1.0
...,...,...,...,...,...,...,...,...,...
17961,B-MAX,2017,8999,Manual,16700,Petrol,150,47.1,1.4
17962,B-MAX,2014,7499,Manual,40700,Petrol,30,57.7,1.0
17963,Focus,2015,9999,Manual,7010,Diesel,20,67.3,1.6
17964,KA,2018,8299,Manual,5007,Petrol,145,57.7,1.2
17965,Focus,2015,8299,Manual,5007,Petrol,22,57.7,1.0

In [6]:
import joblib
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [16]:
df.head(5)

    model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0  Fiesta  2017  12000    Automatic    15944   Petrol  150  57.7         1.0
1   Focus  2018  14000       Manual     9083   Petrol  150  57.7         1.0
2   Focus  2017  13000       Manual    12456   Petrol  150  57.7         1.0
3  Fiesta  2019  17500       Manual    10460   Petrol  145  40.3         1.5
4  Fiesta  2019  16500    Automatic     1482   Petrol  145  48.7         1.0

In [8]:
#1
X = df.drop("price", axis=1)
Y = df["price"]
print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)

Shape of X: (17966, 8)
Shape of Y: (17966,)

In [9]:
#2
categorical_columns = X.select_dtypes(include=["object"]).columns
print("Categorical Columns:")
print(categorical_columns)
X = pd.get_dummies(X, columns=categorical_columns).astype(int)
print("\nFirst 5 rows after encoding:")
print(X.head())

Categorical Columns:
Index(['model', 'transmission', 'fuelType'], dtype='object')

First 5 rows after encoding:
   year  mileage  tax  mpg  engineSize  model_B-MAX  model_C-MAX  \
0  2017    15944  150   57           1            0            0
1  2018     9083  150   57           1            0            0
2  2017    12456  150   57           1            0            0
3  2019    10460  145   40           1            0            0
4  2019     1482  145   48           1            0            0

   model_EcoSport  model_Edge  model_Escort  ...  model_Tourneo Custom  \
0               0           0             0  ...                     0
1               0           0             0  ...                     0
2               0           0             0  ...                     0
3               0           0             0  ...                     0
4               0           0             0  ...                     0

   model_Transit Tourneo  transmission_Automatic  transmission_Manual  \
0                      0                       1                    0
1                      0                       0                    1
2                      0                       0                    1
3                      0                       0                    1
4                      0                       1                    0

   transmission_Semi-Auto  fuelType_Diesel  fuelType_Electric  \
0                       0                0                  0
1                       0                0                  0
2                       0                0                  0
3                       0                0                  0
4                       0                0                  0

   fuelType_Hybrid  fuelType_Other  fuelType_Petrol
0                0               0                1
1                0               0                1
2                0               0                1
3                0               0                1
4                0               0                1

[5 rows x 36 columns]

In [10]:
#3
numerical_columns = ["year", "mileage", "tax", "mpg", "engineSize"]
scaler = StandardScaler()
X[numerical_columns] = scaler.fit_transform(X[numerical_columns])
print("\nFirst 5 rows after scaling:")
print(X.head())

First 5 rows after scaling:
       year   mileage       tax       mpg  engineSize  model_B-MAX  \
0  0.065128 -0.380998  0.591358 -0.042122   -0.447984            0
1  0.552866 -0.733359  0.591358 -0.042122   -0.447984            0
2  0.065128 -0.560132  0.591358 -0.042122   -0.447984            0
3  1.040605 -0.662640  0.510727 -1.721198   -0.447984            0
4  1.040605 -1.123724  0.510727 -0.931045   -0.447984            0

   model_C-MAX  model_EcoSport  model_Edge  model_Escort  ...  \
0            0               0           0             0  ...
1            0               0           0             0  ...
2            0               0           0             0  ...
3            0               0           0             0  ...
4            0               0           0             0  ...

   model_Tourneo Custom  model_Transit Tourneo  transmission_Automatic  \
0                     0                      0                       1
1                     0                      0                       0
2                     0                      0                       0
3                     0                      0                       0
4                     0                      0                       1

   transmission_Manual  transmission_Semi-Auto  fuelType_Diesel  \
0                    0                       0                0
1                    1                       0                0
2                    1                       0                0
3                    1                       0                0
4                    0                       0                0

   fuelType_Electric  fuelType_Hybrid  fuelType_Other  fuelType_Petrol
0                  0                0               0                1
1                  0                0               0                1
2                  0                0               0                1
3                  0                0               0                1
4                  0                0               0                1

[5 rows x 36 columns]

In [11]:
#4
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.33,random_state=42)
print("\nShapes")
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

Shapes
X_train: (12037, 36)
X_test : (5929, 36)
y_train: (12037,)
y_test : (5929,)

In [12]:
#5
model = LinearRegression()
model.fit(X_train, y_train)
print("\nIntercept:")
print(model.intercept_)
print("\nCoefficients:")
print(model.coef_)

Intercept:
17210.917497439557

Coefficients:
[ 2.03818946e+03 -1.31848791e+03 -2.06050222e+01 -9.88971793e+02
  8.79697086e+02 -3.85258470e+03 -2.88119979e+03 -2.56429196e+03
  4.59914526e+03  1.00510970e+04 -2.92630710e+03 -8.36489160e+02
 -3.61467974e+02  1.83738861e+03 -2.61497842e+03  1.61968085e+02
 -4.29324379e+03 -6.76267978e+03 -6.25826661e+02 -1.43413077e+03
  9.16856737e+03  3.36624457e+03  0.00000000e+00  1.68117204e+03
  1.81898940e-12 -4.27251919e+02  1.69790887e+03 -2.98303973e+03
  2.52400422e+02 -2.56788946e+02  4.38852465e+00 -2.00123529e+03
  0.00000000e+00  6.64440783e+03 -1.34128580e+03 -3.30188674e+03]

In [13]:
#6
y_pred = model.predict(X_test)
print("\nFirst 10 Predictions")
print(y_pred[:10])
print("\nFirst 10 Actual Values")
print(y_test.iloc[:10].values)

First 10 Predictions
[ 6886.43611974  9329.53758889  9419.36269037  4494.44391177
  2429.15179332 16980.39203353 28490.75684787 12484.09019267
 11373.10359113 17275.9738973 ]

First 10 Actual Values
[ 6995  8999  7998  5491  3790 18200 22998 11000  7600 14985]

In [15]:
#7
r2 = r2_score(y_test, y_pred)
print("\nR² Score:", r2)
print("\nInterpretation:")
if r2 >= 0.90:
    print("Excellent model performance.")
elif r2 >= 0.75:
    print("Good model performance.")
elif r2 >= 0.50:
    print("Moderate model performance.")
else:
    print("Poor model performance.")

R² Score: 0.8401958871469839

Interpretation:
Good model performance.

In [14]:
#8
joblib.dump(model, "LR_ford_car.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(list(X.columns), "columns.pkl")
print("\nModel and preprocessing files saved successfully.")

Model and preprocessing files saved successfully.