<a href="https://colab.research.google.com/github/sanchitasontakke07-exe/Day_20/blob/main/Task_20(Optional_task).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from google.colab import files
uploaded=files.upload()
df=pd.read_csv("/content/diamond.csv")
df

Saving diamond.csv to diamond (1).csv

     carat        cut color clarity  depth  table  price      x      y      z
0     2.18    Premium     I     SI1   55.2   51.0  14599   8.91   8.78   4.92
1     1.11    Premium     F      IF   62.7   55.6   4930   5.46   5.53   3.42
2     1.09    Premium     G    VVS2   57.2   51.3   7420   5.48   5.46   3.13
3     3.22       Fair     G     SI1   55.8   66.5  20891  18.75  18.97  10.46
4     1.32    Premium     E    VVS1   62.6   69.1   4134   7.99   8.07   5.00
..     ...        ...   ...     ...    ...    ...    ...    ...    ...    ...
995   3.25       Good     E     VS2   56.5   52.3  12139  16.10  16.21   9.10
996   0.60  Very Good     E      IF   57.1   62.4   3693   3.56   3.59   2.03
997   3.46       Fair     I    VVS1   64.0   52.3  13174  21.51  21.37  13.77
998   2.69       Good     G     SI1   61.2   54.7  11861  16.39  16.21  10.03
999   1.11    Premium     G      IF   58.3   59.6   3808   5.17   5.18   3.01

[1000 rows x 10 columns]

In [4]:
df.head()

   carat      cut color clarity  depth  table  price      x      y      z
0   2.18  Premium     I     SI1   55.2   51.0  14599   8.91   8.78   4.92
1   1.11  Premium     F      IF   62.7   55.6   4930   5.46   5.53   3.42
2   1.09  Premium     G    VVS2   57.2   51.3   7420   5.48   5.46   3.13
3   3.22     Fair     G     SI1   55.8   66.5  20891  18.75  18.97  10.46
4   1.32  Premium     E    VVS1   62.6   69.1   4134   7.99   8.07   5.00

In [6]:
#1
X = df.drop("price", axis=1)
Y = df["price"]
print("Shape of X:", X.shape)
print("Shape of Y:", Y.shape)

Shape of X: (1000, 9)
Shape of Y: (1000,)

In [7]:
#2
X = df.drop("price", axis=1)
categorical_columns = X.select_dtypes(include=['object']).columns
print("Categorical Columns:")
print(categorical_columns)
X_encoded = pd.get_dummies(X, columns=categorical_columns)
X_encoded = X_encoded.astype(int)
print("\nFirst 5 Rows After One-Hot Encoding:")
print(X_encoded.head())

Categorical Columns:
Index(['cut', 'color', 'clarity'], dtype='object')

First 5 Rows After One-Hot Encoding:
   carat  depth  table   x   y   z  cut_Fair  cut_Good  cut_Ideal  \
0      2     55     51   8   8   4         0         0          0
1      1     62     55   5   5   3         0         0          0
2      1     57     51   5   5   3         0         0          0
3      3     55     66  18  18  10         1         0          0
4      1     62     69   7   8   5         0         0          0

   cut_Premium  ...  color_I  color_J  clarity_I1  clarity_IF  clarity_SI1  \
0            1  ...        1        0           0           0            1
1            1  ...        0        0           0           1            0
2            1  ...        0        0           0           0            0
3            0  ...        0        0           0           0            1
4            1  ...        0        0           0           0            0

   clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2
0            0            0            0             0             0
1            0            0            0             0             0
2            0            0            0             0             1
3            0            0            0             0             0
4            0            0            0             1             0

[5 rows x 26 columns]

In [9]:
#3
from sklearn.preprocessing import StandardScaler
X = df.drop("price", axis=1)
categorical_columns = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X, columns=categorical_columns).astype(int)
numerical_columns = ['carat', 'depth', 'table', 'x', 'y', 'z']
scaler = StandardScaler()
X[numerical_columns] = scaler.fit_transform(X[numerical_columns])
print("First 5 Rows After Feature Scaling:")
print(X.head())

First 5 Rows After Feature Scaling:
      carat     depth     table         x         y         z  cut_Fair  \
0  0.582370 -1.575321 -1.477748 -0.319980 -0.321176 -0.498575         0
1 -0.391493  0.858950 -0.782910 -0.857461 -0.858859 -0.794115         0
2 -0.391493 -0.879815 -1.477748 -0.857461 -0.858859 -0.794115         0
3  1.556234 -1.575321  1.127897  1.471622  1.471102  1.274662         1
4 -0.391493  0.858950  1.649026 -0.499140 -0.321176 -0.203036         0

   cut_Good  cut_Ideal  cut_Premium  ...  color_I  color_J  clarity_I1  \
0         0          0            1  ...        1        0           0
1         0          0            1  ...        0        0           0
2         0          0            1  ...        0        0           0
3         0          0            0  ...        0        0           0
4         0          0            1  ...        0        0           0

   clarity_IF  clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  \
0           0            1            0            0            0
1           1            0            0            0            0
2           0            0            0            0            0
3           0            1            0            0            0
4           0            0            0            0            0

   clarity_VVS1  clarity_VVS2
0             0             0
1             0             0
2             0             1
3             0             0
4             1             0

[5 rows x 26 columns]

In [15]:
#4
from sklearn.model_selection import train_test_split
X = df.drop("price", axis=1)
y = df["price"]
categorical_columns = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X, columns=categorical_columns).astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.33,random_state=42)
print("Shape of X_train:", X_train.shape)
print("Shape of X_test :", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test :", y_test.shape)

Shape of X_train: (670, 26)
Shape of X_test : (330, 26)
Shape of y_train: (670,)
Shape of y_test : (330,)

In [17]:
#5
from sklearn.linear_model import LinearRegression
X = df.drop("price", axis=1)
y = df["price"]
categorical_columns = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X, columns=categorical_columns).astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.33,random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
print("Intercept:")
print(model.intercept_)
print("\nCoefficients:")
for feature, coef in zip(X_train.columns, model.coef_):
    print(feature, ":", coef)

Intercept:
2055.4945277265133

Coefficients:
carat : 2737.5796082887514
depth : -24.665688371049384
table : 17.91454644187884
x : -164.01198487477953
y : 659.2940533193963
z : -224.46368527066352
cut_Fair : 422.407911799048
cut_Good : -194.34793576351848
cut_Ideal : -172.0252445787208
cut_Premium : -63.61004587303886
cut_Very Good : 7.575314416230752
color_D : -239.84700118954882
color_E : -419.1046206794037
color_F : 488.63074338263607
color_G : -391.15431770048474
color_H : 281.43721538403946
color_I : -261.8298677772747
color_J : 541.8678485800368
clarity_I1 : -398.6678208189347
clarity_IF : -177.03642890708528
clarity_SI1 : 287.7886547649569
clarity_SI2 : 102.28063400290173
clarity_VS1 : 111.47648004825793
clarity_VS2 : 48.364178356904326
clarity_VVS1 : 191.25662731536113
clarity_VVS2 : -165.46232476236236

In [25]:
#6
categorical_columns = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X, columns=categorical_columns).astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.33,random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("First 10 Predicted Values:")
print(y_pred[:10])
print("\nFirst 10 Actual Values:")
print(y_test.iloc[:10].values)

First 10 Predicted Values:
[11311.23669077 14840.91247804  2277.78997084  8252.10709592
  3582.44660127  6240.87682353  2810.33996669  1544.36668687
 15824.92626102  1838.67402211]

First 10 Actual Values:
[ 9027 23332  3772  6060  3546  5455  4628   793 15694  2375]

In [22]:
#7
from sklearn.metrics import r2_score
categorical_columns = X.select_dtypes(include=['object']).columns
X = pd.get_dummies(X, columns=categorical_columns).astype(int)
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.33,random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.6857225349402651

In [26]:
import joblib
joblib.dump(model, "LR_diamond.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "columns.pkl")
print("Model and preprocessing objects saved successfully!")

Model and preprocessing objects saved successfully!